// Generated by: main
// TypeWriter: slice
// Directive: +gen on Description

package tag

// DescriptionSlice is a slice of type Description. Use it where you would use []Description.
type DescriptionSlice []Description
